"""Simple presentation generator: convert an essay/text into a PowerPoint file.

Usage:
    from actions.presentation_generator import create_presentation_from_text
    path = create_presentation_from_text(text, output_path="slides.pptx", title="My Talk")

This implementation uses a lightweight heuristic to split the text into paragraphs
and sentences and places the first sentence as a heading and subsequent sentences as
bullet points. It uses `python-pptx` to create the .pptx file.
"""
from typing import Optional, List
import re
import os

from pptx import Presentation
from pptx.util import Inches, Pt


def _split_into_sentences(text: str) -> List[str]:
    # Very small sentence splitter using punctuation.
    parts = re.split(r'(?<=[.!?])\s+', text.strip())
    cleaned = [p.replace('\n', ' ').strip() for p in parts if p.strip()]
    return cleaned


def _chunk_bullets(bullets: List[str], max_per_slide: int) -> List[List[str]]:
    chunks = []
    for i in range(0, len(bullets), max_per_slide):
        chunks.append(bullets[i:i + max_per_slide])
    return chunks


def create_presentation_from_text(text: str,
                                  output_path: str = "presentation.pptx",
                                  title: Optional[str] = None,
                                  max_bullets: int = 5) -> str:
    """Create a PowerPoint presentation from the provided text.

    - The first non-empty line (or provided `title`) is used as the title slide.
    - The body is split into paragraphs (blank-line separated). Each paragraph is
      split into sentences; the first sentence becomes a heading and the rest become
      bullet points. If there are more bullets than `max_bullets`, multiple slides
      are created for that paragraph.

    Returns the path to the saved .pptx file.
    """
    if not text or not text.strip():
        raise ValueError("text must be a non-empty string")

    prs = Presentation()

    # Title slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    slide_title = slide.shapes.title
    subtitle = slide.placeholders[1] if len(slide.placeholders) > 1 else None

    if title:
        slide_title.text = title
    else:
        # infer title from first non-empty line
        first_line = next((ln.strip() for ln in text.splitlines() if ln.strip()), None)
        slide_title.text = first_line[:80] if first_line else "Presentation"

    if subtitle is not None:
        subtitle.text = "Generated by Jarvis"

    # Split into paragraphs by blank lines
    paragraphs = [p.strip() for p in re.split(r'\n\s*\n', text) if p.strip()]

    for para in paragraphs:
        sentences = _split_into_sentences(para)
        if not sentences:
            continue

        heading = sentences[0]
        bullets = sentences[1:] if len(sentences) > 1 else sentences

        if not bullets:
            # If a paragraph is a single long sentence, try splitting into shorter chunks
            words = heading.split()
            approx = max(1, len(words) // 12)
            bullets = [" ".join(words[i:i + approx]) for i in range(0, len(words), approx)]
            heading = bullets.pop(0) if bullets else heading

        chunks = _chunk_bullets(bullets, max_bullets) or [["."]]

        for idx, chunk in enumerate(chunks):
            # Use a title + content layout
            try:
                content_slide_layout = prs.slide_layouts[1]
            except Exception:
                content_slide_layout = prs.slide_layouts[0]

            s = prs.slides.add_slide(content_slide_layout)
            s.shapes.title.text = heading if idx == 0 else f"{heading} (cont.)"

            # Find the body placeholder (commonly placeholder index 1)
            body = None
            for shape in s.placeholders:
                if shape.placeholder_format.type == 1:
                    body = shape
                    break

            if body is None:
                # fallback: try placeholder index 1
                body = s.placeholders[1] if len(s.placeholders) > 1 else None

            if body is None:
                # skip if we can't find a content placeholder
                continue

            tf = body.text_frame
            tf.clear()
            for b in chunk:
                p = tf.add_paragraph()
                p.text = b.strip()
                p.level = 0
                p.font = p.font  # type: ignore

    # Optionally add a summary slide
    summary = prs.slides.add_slide(prs.slide_layouts[1])
    summary.shapes.title.text = "Summary"
    tf = summary.placeholders[1].text_frame
    tf.clear()
    tf.add_paragraph().text = "Generated with Jarvis — review slides for clarity and edit as needed."

    # Ensure output directory exists
    outdir = os.path.dirname(os.path.abspath(output_path))
    if outdir and not os.path.exists(outdir):
        os.makedirs(outdir, exist_ok=True)

    prs.save(output_path)
    return os.path.abspath(output_path)


if __name__ == "__main__":
    # Simple smoke test when run directly
    sample = (
        "Title: Sample Talk\n\n"
        "This is the introduction. It explains what we'll cover.\n\n"
        "First point. This contains a couple of sentences to show bullets. More detail here.\n\n"
        "Conclusion. Wrap up and next steps."
    )
    out = create_presentation_from_text(sample, output_path="tmp_sample_presentation.pptx", title="Sample Talk")
    print(f"Saved presentation to: {out}")
